name: GitHub Actions Demo
on:
  push:
    branches: [master]
jobs:
  Client-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: cd client && npm install
      - run: cd client && npm run test

  Deploy:
    needs: [Client-Tests]
    runs-on: ubuntu-latest
    steps:
      - run: curl https://api.render.com/deploy/srv-c7pb6ehg7hp8d073d9qg?key=PVvurWUF3kk